### ISSUE TITLE
Discussion:  Moving `gmusic.js` to an extensible ES6 style

### ISSUE THREAD

**Issue by MarshallOfSound** [gmusic-utils/meta#5]
Current `gmusic.js` is a bit messy.  All of our namespaces and methods are in one file, all the selectors are in that file as well.  Realisticly we should have separate files for each namespace.

I would like to propose that we (me) port `gmusic.js` to the same style of files as `gmusic-ui.js` (with a couple of technicaly structure tweaks).

The main goal of this port is to
- Make the learning curve in contributing to the repo much easier
- Provide a simple API (the `GMusicNamespace` class) to extend the `GMusic` prototype
- Clean up the code in general by splitting the namespaces into modules
- Move the binding logic away from us and onto the ES6 transpilers

I'm keen to do this, just looking for feedback before I start to tackle it.

For those unfamiliar with how `GMusic-UI.js` works we have a base [`GMusicNamespace`](https://github.com/gmusic-utils/gmusic-ui.js/blob/master/src/GMusicNamespace.js) class which all our namespaces extend.  You then call `addMethod` within the namespace to make a method public and everything else is handled behind the scenes.

/cc @gmusic-utils/gmusic-js @gmusic-utils/gmusic-ui-js

**Comment by MarshallOfSound** [comment]
As part of this move it would also be quite simple to move to in-code docs. And use a tool like [ESDoc](https://esdoc.org/) to automatically generate us documentation and host it in GitHub pages or similar.

I also want to have a discussion regarding whether all our events should be emitted off the top level `GMusic` class or whether each namespace should emit their own events?

**Comment by twolfson** [comment]
As a heads up, this should have been opened on `gmusic.js` since it's specific to the repo, not organization.

With respect to changing the code base, here's my list of pros and cons:

**Pros of ES5:**
- Current code base is relatively stable
- Wider recognition by wider audience (not everyone at every company has been switching to ES6)
- Compiled result is almost verbatim as input result (leading to simple debugging)

**Cons of ES5 (with respect to ES6):**
- Don't have `class` syntax
  - Counterpoint: `gmusic.js` doesn't use classes, it emulates namespaces
  - Counterpoint: We already have a class-esque namespace system via `init` functions

In my opinion, this is a request for stylistic comfort which is never a good reason to make a technical decision. For example, would you rewrite an entire code base from `snake_case` to `camelCase` because you used `camelCase` at your last company?

I should note that there is a counterpoint about organizational consistency with the same language (e.g. all repos should be in the same style). However, I have expressed my opposition to using ES6 in the past so that fragmentation has already occurred.

**Comment by twolfson** [comment]
As you might have noticed, I didn't address all your points. That's because I believe those are tangential to ES5/ES6. Here are my specific arguments for those:
- Breaking down into separate files
  - This can occur at any time regardless of ES5/ES6
  - The single file structure was chosen because it is easier to comprehend/jump around a single file rather than try to recall "where did we store that function?" every time code is being edited (e.g. hooks and methods share logic/selectors)
  - When that file becomes unwieldy, then it is reasonable to request to break it down into further parts and possibly choose another architecture
- With respect to "clean up the code" in the style of `gmusic-ui.js`, I honestly see nothing more than a thin wrapper class distinguishing the 2
- With respect to automated documentation (e.g. ESDoc), there are plenty of non-ES6 based tools like JSDoc. The decision to write manual documentation is been a personal one; I find more flexibility from external documentation (e.g. I can provide examples) and not bloat up the code (e.g. examples can get bulky)

**Comment by jacobwgillespie** [comment]
To throw a few more points into the ring:
- ES6 would in a way be future-looking, i.e. the language itself is moving towards global ES6 support, so moving this library (like many others) over to ES6 benefits people in environments that support ES6 natively as well as such environments in the future.  It would also be promoting ES6 (/next) development which could be viewed as a positive and might attract quality contributions from the community.
- ES6 would enable tree-shaking thanks to static dependencies.

**Comment by twolfson** [comment]
Counterpoints:
- With respect to ES6 transition being future-looking, I already addressed those via:
  - Current code base is relatively stable
  - Wider recognition by wider audience (not everyone at every company has been switching to ES6)
  - Compiled result is almost verbatim as input result (leading to simple debugging)
- With respect to tree-shaking, that's nothing specific to ES6; tree-shaking is identifying unused variables/methods in the AST. This can be done in ES5 as well and has been discussed in `browserify` (although I haven't researched it yet).
  - However, I should note that there is 1 dependency (`inherits`) and it's intentionally light as we are a browser library so tree-shaking doesn't do much for us

**Comment by jacobwgillespie** [comment]
On those two:
- Yep, agreed, though I mean more that it's future looking in regards to the language (as in, JS is moving towards ESnext)
- On tree-shaking, I mean that consumers of our library can utilize tree-shaking, not necessarily that we'd benefit from it as you said.  And it probably doesn't provide massive gains in size savings, but still it's a nice to have.

**Comment by MarshallOfSound** [comment]
I'll address the points raised one by one

> Current code base is relatively stable

Yes, the current code base is stable, this includes the tests.  Moving to a new framework should retain our conistancy and stability as our test suite should prevent regressions.

> Wider recognition by wider audience (not everyone at every company has been switching to ES6)

This I can somewhat agree with but I will address the uptake of ES6 further down

> Compiled result is almost verbatim as input result (leading to simple debugging)

Although people seem to think debugging compiled ES6 is outstandingly difficult it is suprisingly easy.  Lots of the variables just end up with underscores either side of their name and not much else changes.

> We already have a class-esque namespace system via init functions

Why use a "class-esque" system which we wrote ourselves when we can use the proper Javascript class system with proper classes and constructors which are universally understood.

> In my opinion, this is a request for stylistic comfort which is never a good reason to make a technical decision. For example, would you rewrite an entire code base from snake_case to camelCase because you used camelCase at your last company?

You misunderstand the proposal, this isn't a stylistic comfort issue.  I've been comfortable with the ES5 implementation the whole time I've been in this repo.  However, ES6 is the **new** standard of Javascript and as such shouldn't be looked at as a _stylistic_ change rather a future proofing and _getting up to date_ change.  ES6 is the future of Javascript and it's better to get on board now than later into the game.

> I should note that there is a counterpoint about organizational consistency with the same language (e.g. all repos should be in the same style). However, I have expressed my opposition to using ES6 in the past so that fragmentation has already occurred.

The reason the new repos I started are written in ES6 is the same reasoning as above.  ES6 is the future of JS, starting a new repo in ES5 makes very little sense at the moment.  Whereas porting an ES5 repo over to ES6 makes a lot of sense.

> Breaking down into separate files

This was more of a side point and not related entirely to the move to ES6.  But to clarify the intention, each namespace would be in it's own file and Selectors and methods would be contained inside a namespace.

> With respect to automated documentation (e.g. ESDoc), there are plenty of non-ES6 based tools like JSDoc. The decision to write manual documentation is been a personal one; I find more flexibility from external documentation (e.g. I can provide examples) and not bloat up the code (e.g. examples can get bulky)

Yeah this was another side point, JSDoc and ESDoc actually follow the same syntax.  I'm OK with either but I was just querying what we thought of that idea :+1:

Thanks for the feedback people

**Comment by jostrander** [comment]
Not sure if this is still open for debate. However as someone who has briefly contributed to the library I would like to also see this move towards ES6 at the very least.  At ~500+ lines the code isn't _chaotic_ but it certainly was a chore to contribute initially due to everything being scattered around the same file. The documentation was equally a chore to edit, if not worse, even in a markdown editor due to the large file size. I believe that moving to internal documentation for methods/etc would be better for maintainability, and then putting examples into their own documentation file would be better.

**Comment by twolfson** [comment]
We have already established that transitioning to ES6 and breaking up the
library/documentation are separate concepts. If we would like to continue
that discussion, then it should be on a separate issue (as this one is for
ES6).

Also, please create that issue in gmusic.js not this repo -_-;;
